nice python interpret_cli.py "data/glove/glove.6B.300d.txt" "data/semcat/Categories/" -dense --lines_to_read=50000 --weights_dir="out/rng/gauss/kernel_01/" -save_weights --processes=20 --name="01" --kde_kernel="gaussian" --kde_bandwidth=0.1 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;
nice python interpret_cli.py "out/rng/gauss/kernel_01/01_I.embedding.100d.txt" "data/semcat/Categories/" -dense --lines_to_read=50000 --weights_dir="out/rng/gauss/kernel_01/" -save_weights --processes=20 --name="s01" --kde_kernel="gaussian" --kde_bandwidth=0.1 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;

nice python interpret_cli.py "data/glove/glove.6B.300d.txt" "data/semcat/Categories/" -dense --lines_to_read=50000 --weights_dir="out/rng/gauss/kernel_02/" -save_weights --processes=20 --name="02" --kde_kernel="gaussian" --kde_bandwidth=0.1 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;
nice python interpret_cli.py "out/rng/gauss/kernel_02/02_I.embedding.100d.txt" "data/semcat/Categories/" -dense --lines_to_read=50000 --weights_dir="out/rng/gauss/kernel_02/" -save_weights --processes=20 --name="s02" --kde_kernel="gaussian" --kde_bandwidth=0.1 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;

nice python interpret_cli.py "data/glove/glove.6B.300d.txt" "data/semcat/Categories/" -dense --lines_to_read=50000 --weights_dir="out/rng/gauss/kernel_05/" -save_weights --processes=20 --name="05" --kde_kernel="gaussian" --kde_bandwidth=0.5 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;
nice python interpret_cli.py "out/rng/gauss/kernel_05/05_I.embedding.100d.txt" "data/semcat/Categories/" -dense --lines_to_read=50000 --weights_dir="out/rng/gauss/kernel_05/" -save_weights --processes=20 --name="s05" --kde_kernel="gaussian" --kde_bandwidth=0.5 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;

nice python interpret_cli.py "data/glove/glove.6B.300d.txt" "data/semcat/Categories/" -dense --lines_to_read=50000 --weights_dir="out/rng/gauss/kernel_1/" -save_weights --processes=20 --name="1" --kde_kernel="gaussian" --kde_bandwidth=1 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;
nice python interpret_cli.py "out/rng/gauss/kernel_1/1_I.embedding.100d.txt" "data/semcat/Categories/" -dense --lines_to_read=50000 --weights_dir="out/rng/gauss/kernel_1/" -save_weights --processes=20 --name="s1" --kde_kernel="gaussian" --kde_bandwidth=1 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;

nice python interpret_cli.py "data/glove/sparse/glove300d_l_0.1_DL_top50000.emb.gz" "data/semcat/Categories/" --lines_to_read=50000 --weights_dir="out/rng/gauss/sparse/l01/" -save_weights --processes=20 --name="l" --kde_kernel="gaussian" --kde_bandwidth=0.2 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;
gzip out/rng/gauss/sparse/l01/l_I.embedding.100d.txt;
nice python interpret_cli.py "out/rng/gauss/sparse/l01/l_I.embedding.100d.txt.gz" "data/semcat/Categories/" --lines_to_read=50000 --weights_dir="out/rng/gauss/sparse/l01/" -save_weights --processes=20 --name="sl" --kde_kernel="gaussian" --kde_bandwidth=0.2 -random_drop --random_seed=420 --percent=0.4 --calculate="score" --calculation_args 10;
